// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Staticaly.Server.Models;

#nullable disable

namespace Staticaly.Server.ModelsMigrations
{
    [DbContext(typeof(StaticalyContext))]
    [Migration("20240226230846_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Staticaly.Server.Models.Rango", b =>
                {
                    b.Property<int>("RangoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RangoID"));

                    b.Property<string>("NombreRango")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("PuntosMax")
                        .HasColumnType("int");

                    b.Property<int>("PuntosMin")
                        .HasColumnType("int");

                    b.HasKey("RangoID");

                    b.ToTable("Rangos");

                    b.HasData(
                        new
                        {
                            RangoID = 1,
                            NombreRango = "Nuevo",
                            PuntosMax = 99,
                            PuntosMin = 0
                        },
                        new
                        {
                            RangoID = 2,
                            NombreRango = "Viajero",
                            PuntosMax = 5000,
                            PuntosMin = 100
                        },
                        new
                        {
                            RangoID = 3,
                            NombreRango = "Explorador",
                            PuntosMax = 10000,
                            PuntosMin = 5001
                        },
                        new
                        {
                            RangoID = 4,
                            NombreRango = "Navegante",
                            PuntosMax = 15000,
                            PuntosMin = 10001
                        },
                        new
                        {
                            RangoID = 5,
                            NombreRango = "Analista",
                            PuntosMax = 20000,
                            PuntosMin = 15001
                        },
                        new
                        {
                            RangoID = 6,
                            NombreRango = "Estadistico",
                            PuntosMax = 25000,
                            PuntosMin = 20001
                        },
                        new
                        {
                            RangoID = 7,
                            NombreRango = "Coordinador",
                            PuntosMax = 30000,
                            PuntosMin = 25001
                        },
                        new
                        {
                            RangoID = 8,
                            NombreRango = "Arquitecto",
                            PuntosMax = 35000,
                            PuntosMin = 30001
                        },
                        new
                        {
                            RangoID = 9,
                            NombreRango = "Maestro",
                            PuntosMax = 40000,
                            PuntosMin = 35001
                        },
                        new
                        {
                            RangoID = 10,
                            NombreRango = "Guardian",
                            PuntosMax = 100000,
                            PuntosMin = 40001
                        });
                });

            modelBuilder.Entity("Staticaly.Server.Models.Rol", b =>
                {
                    b.Property<int>("RolID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RolID"));

                    b.Property<string>("RolName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RolID");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RolID = 1,
                            RolName = "Admin"
                        },
                        new
                        {
                            RolID = 2,
                            RolName = "Estudiante"
                        },
                        new
                        {
                            RolID = 3,
                            RolName = "Docente"
                        });
                });

            modelBuilder.Entity("Staticaly.Server.Models.User", b =>
                {
                    b.Property<int>("UsuarioID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsuarioID"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("EmailVerified")
                        .HasColumnType("bit");

                    b.Property<byte[]>("Imagen")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Puntos")
                        .HasColumnType("int");

                    b.Property<int>("RangoID")
                        .HasColumnType("int");

                    b.Property<int>("RolID")
                        .HasColumnType("int");

                    b.Property<string>("VerificationToken")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("UsuarioID");

                    b.HasIndex("RangoID");

                    b.HasIndex("RolID");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Staticaly.Server.Models.User", b =>
                {
                    b.HasOne("Staticaly.Server.Models.Rango", "Rango")
                        .WithMany()
                        .HasForeignKey("RangoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Staticaly.Server.Models.Rol", "Rol")
                        .WithMany()
                        .HasForeignKey("RolID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rango");

                    b.Navigation("Rol");
                });
#pragma warning restore 612, 618
        }
    }
}
