// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Staticaly.Server.Models;

#nullable disable

namespace Staticaly.Server.ModelsMigrations
{
    [DbContext(typeof(StaticalyContext))]
    [Migration("20240606024220_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Staticaly.Server.Models.Calificaciones", b =>
                {
                    b.Property<int>("CalificacionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CalificacionID"));

                    b.Property<float?>("Calificacion")
                        .IsRequired()
                        .HasColumnType("real");

                    b.Property<int>("ComentarioID")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioID")
                        .HasColumnType("int");

                    b.HasKey("CalificacionID");

                    b.HasIndex("ComentarioID");

                    b.HasIndex("UsuarioID");

                    b.ToTable("Calificaciones");
                });

            modelBuilder.Entity("Staticaly.Server.Models.Comentarios", b =>
                {
                    b.Property<int>("ComentarioID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ComentarioID"));

                    b.Property<float?>("Calificacion")
                        .HasColumnType("real");

                    b.Property<string>("Contenido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Fecha")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("Imagen")
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("PublicacionID")
                        .HasColumnType("int");

                    b.Property<int>("Reportes")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioID")
                        .HasColumnType("int");

                    b.HasKey("ComentarioID");

                    b.HasIndex("PublicacionID");

                    b.HasIndex("UsuarioID");

                    b.ToTable("Comentarios");
                });

            modelBuilder.Entity("Staticaly.Server.Models.Cuestionarios", b =>
                {
                    b.Property<int>("CuestionarioID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CuestionarioID"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EquipoID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaCierre")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Publicado")
                        .HasColumnType("bit");

                    b.Property<int>("Respuestas")
                        .HasColumnType("int");

                    b.Property<int?>("RespuestasMaximas")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("UsuarioID")
                        .HasColumnType("int");

                    b.HasKey("CuestionarioID");

                    b.HasIndex("EquipoID");

                    b.HasIndex("UsuarioID");

                    b.ToTable("Cuestionarios");
                });

            modelBuilder.Entity("Staticaly.Server.Models.DatosSubProyecto", b =>
                {
                    b.Property<int>("DatosSubProyectoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DatosSubProyectoID"));

                    b.Property<int?>("Cantidad")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("SubproyectoID")
                        .HasColumnType("int");

                    b.HasKey("DatosSubProyectoID");

                    b.HasIndex("SubproyectoID");

                    b.ToTable("DatosSubProyecto");
                });

            modelBuilder.Entity("Staticaly.Server.Models.Ejercicios", b =>
                {
                    b.Property<int>("EjerciciosID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EjerciciosID"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EquipoID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaCierre")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Publicado")
                        .HasColumnType("bit");

                    b.Property<int>("PuntosAquitar")
                        .HasColumnType("int");

                    b.Property<int>("PuntosMin")
                        .HasColumnType("int");

                    b.Property<int>("Timer")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("UsuarioID")
                        .HasColumnType("int");

                    b.Property<bool>("permitirMasDeUnaRespuesta")
                        .HasColumnType("bit");

                    b.HasKey("EjerciciosID");

                    b.HasIndex("UsuarioID");

                    b.ToTable("Ejercicios");

                    b.HasData(
                        new
                        {
                            EjerciciosID = 1,
                            Descripcion = "En base a estos ejercicios sera el rango que tengas dentro de la plataforma, hay un total de 100 ejercicios los cuales van a ir incrementando su dificultad conforme vayas avanzando, por cada respuesta incorrecta se restaran puntos y por cada segundo que pase se restaran puntos, por lo que es importante que contestes lo mas rapido posible y de manera correcta.",
                            EquipoID = 1,
                            Publicado = true,
                            PuntosAquitar = 100,
                            PuntosMin = 100,
                            Timer = 1000,
                            Titulo = "Ejercicios Publicos",
                            UsuarioID = 1,
                            permitirMasDeUnaRespuesta = true
                        });
                });

            modelBuilder.Entity("Staticaly.Server.Models.EjerciciosPreguntas", b =>
                {
                    b.Property<int>("EjerciciosPreguntasID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EjerciciosPreguntasID"));

                    b.Property<int>("EjercicioID")
                        .HasColumnType("int");

                    b.Property<byte[]>("Imagen")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Pregunta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Puntos")
                        .HasColumnType("int");

                    b.Property<string>("Respuesta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EjerciciosPreguntasID");

                    b.HasIndex("EjercicioID");

                    b.ToTable("EjerciciosPreguntas");

                    b.HasData(
                        new
                        {
                            EjerciciosPreguntasID = 1,
                            EjercicioID = 1,
                            Pregunta = "Media (Promedio) Datos: 15, 20, 25, 30, 35.",
                            Puntos = 1000,
                            Respuesta = "25"
                        },
                        new
                        {
                            EjerciciosPreguntasID = 2,
                            EjercicioID = 1,
                            Pregunta = "Mediana Datos: 8, 4, 6, 12, 10",
                            Puntos = 1000,
                            Respuesta = "8"
                        },
                        new
                        {
                            EjerciciosPreguntasID = 3,
                            EjercicioID = 1,
                            Pregunta = "Moda Datos: 7, 4, 7, 9, 2, 4.",
                            Puntos = 1000,
                            Respuesta = "7"
                        },
                        new
                        {
                            EjerciciosPreguntasID = 4,
                            EjercicioID = 1,
                            Pregunta = "Varianza Datos: 5, 10, 15, 20, 25. ",
                            Puntos = 1000,
                            Respuesta = "50"
                        },
                        new
                        {
                            EjerciciosPreguntasID = 5,
                            EjercicioID = 1,
                            Pregunta = "5.	Desviación Estándar Datos: 9, 12, 15, 18, 21",
                            Puntos = 1000,
                            Respuesta = "7.07"
                        });
                });

            modelBuilder.Entity("Staticaly.Server.Models.EjerciciosRespuestas", b =>
                {
                    b.Property<int>("EjerciciosRespuestasID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EjerciciosRespuestasID"));

                    b.Property<bool?>("Correcta")
                        .HasColumnType("bit");

                    b.Property<int>("EjercicioID")
                        .HasColumnType("int");

                    b.Property<int>("EjercicioPreguntaID")
                        .HasColumnType("int");

                    b.Property<int>("Puntos")
                        .HasColumnType("int");

                    b.Property<string>("Respuesta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UsuarioID")
                        .HasColumnType("int");

                    b.HasKey("EjerciciosRespuestasID");

                    b.HasIndex("EjercicioPreguntaID");

                    b.HasIndex("UsuarioID");

                    b.ToTable("EjerciciosRespuestas");
                });

            modelBuilder.Entity("Staticaly.Server.Models.Equipos", b =>
                {
                    b.Property<int>("EquipoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EquipoID"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("TipoEquipoID")
                        .HasColumnType("int");

                    b.HasKey("EquipoID");

                    b.HasIndex("TipoEquipoID");

                    b.ToTable("Equipos");

                    b.HasData(
                        new
                        {
                            EquipoID = 1,
                            Nombre = "Foro Publico",
                            TipoEquipoID = 1
                        });
                });

            modelBuilder.Entity("Staticaly.Server.Models.OpcionesCuestionario", b =>
                {
                    b.Property<int>("OpcionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OpcionID"));

                    b.Property<string>("Opcion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("PreguntaID")
                        .HasColumnType("int");

                    b.HasKey("OpcionID");

                    b.HasIndex("PreguntaID");

                    b.ToTable("OpcionesCuestionario");
                });

            modelBuilder.Entity("Staticaly.Server.Models.Permisos", b =>
                {
                    b.Property<int>("PermisoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PermisoID"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("PermisoID");

                    b.ToTable("Permisos");

                    b.HasData(
                        new
                        {
                            PermisoID = 1,
                            Nombre = "Administrar"
                        },
                        new
                        {
                            PermisoID = 2,
                            Nombre = "Visualizar"
                        },
                        new
                        {
                            PermisoID = 3,
                            Nombre = "Editar"
                        });
                });

            modelBuilder.Entity("Staticaly.Server.Models.Preguntas", b =>
                {
                    b.Property<int>("PreguntaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PreguntaID"));

                    b.Property<int>("CuestionarioID")
                        .HasColumnType("int");

                    b.Property<string>("Pregunta")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("PreguntaID");

                    b.HasIndex("CuestionarioID");

                    b.ToTable("Preguntas");
                });

            modelBuilder.Entity("Staticaly.Server.Models.Proyectos", b =>
                {
                    b.Property<int>("ProyectoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProyectoID"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("EquipoID")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("UsuarioID")
                        .HasColumnType("int");

                    b.HasKey("ProyectoID");

                    b.HasIndex("EquipoID");

                    b.HasIndex("UsuarioID");

                    b.ToTable("Proyectos");
                });

            modelBuilder.Entity("Staticaly.Server.Models.Publicaciones", b =>
                {
                    b.Property<int>("PublicacionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PublicacionID"));

                    b.Property<string>("Contenido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("ForoID")
                        .HasColumnType("int");

                    b.Property<byte[]>("Imagen")
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("Reportes")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("UsuarioID")
                        .HasColumnType("int");

                    b.HasKey("PublicacionID");

                    b.HasIndex("UsuarioID");

                    b.ToTable("Publicaciones");
                });

            modelBuilder.Entity("Staticaly.Server.Models.Rango", b =>
                {
                    b.Property<int>("RangoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RangoID"));

                    b.Property<string>("NombreRango")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<int>("PuntosMax")
                        .HasColumnType("int");

                    b.Property<int>("PuntosMin")
                        .HasColumnType("int");

                    b.HasKey("RangoID");

                    b.ToTable("Rangos");

                    b.HasData(
                        new
                        {
                            RangoID = 1,
                            NombreRango = "Nuevo",
                            PuntosMax = 99,
                            PuntosMin = 0
                        },
                        new
                        {
                            RangoID = 2,
                            NombreRango = "Viajero",
                            PuntosMax = 5000,
                            PuntosMin = 100
                        },
                        new
                        {
                            RangoID = 3,
                            NombreRango = "Explorador",
                            PuntosMax = 10000,
                            PuntosMin = 5001
                        },
                        new
                        {
                            RangoID = 4,
                            NombreRango = "Navegante",
                            PuntosMax = 15000,
                            PuntosMin = 10001
                        },
                        new
                        {
                            RangoID = 5,
                            NombreRango = "Analista",
                            PuntosMax = 20000,
                            PuntosMin = 15001
                        },
                        new
                        {
                            RangoID = 6,
                            NombreRango = "Estadistico",
                            PuntosMax = 25000,
                            PuntosMin = 20001
                        },
                        new
                        {
                            RangoID = 7,
                            NombreRango = "Coordinador",
                            PuntosMax = 30000,
                            PuntosMin = 25001
                        },
                        new
                        {
                            RangoID = 8,
                            NombreRango = "Arquitecto",
                            PuntosMax = 35000,
                            PuntosMin = 30001
                        },
                        new
                        {
                            RangoID = 9,
                            NombreRango = "Maestro",
                            PuntosMax = 40000,
                            PuntosMin = 35001
                        },
                        new
                        {
                            RangoID = 10,
                            NombreRango = "Guardian",
                            PuntosMax = 100000,
                            PuntosMin = 40001
                        });
                });

            modelBuilder.Entity("Staticaly.Server.Models.Reportes", b =>
                {
                    b.Property<int>("ReportesID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReportesID"));

                    b.Property<int>("ComentarioID")
                        .HasColumnType("int");

                    b.Property<int>("PublicacionID")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioID")
                        .HasColumnType("int");

                    b.HasKey("ReportesID");

                    b.HasIndex("ComentarioID");

                    b.HasIndex("PublicacionID");

                    b.HasIndex("UsuarioID");

                    b.ToTable("Reportes");
                });

            modelBuilder.Entity("Staticaly.Server.Models.RespuestasCuestionario", b =>
                {
                    b.Property<int>("RespuestasCuestionarioID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RespuestasCuestionarioID"));

                    b.Property<int>("CuestionarioID")
                        .HasColumnType("int");

                    b.Property<int>("PreguntaID")
                        .HasColumnType("int");

                    b.Property<int>("RespuestaID")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioID")
                        .HasColumnType("int");

                    b.HasKey("RespuestasCuestionarioID");

                    b.HasIndex("UsuarioID");

                    b.ToTable("RespuestasCuestionarios");
                });

            modelBuilder.Entity("Staticaly.Server.Models.Rol", b =>
                {
                    b.Property<int>("RolID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RolID"));

                    b.Property<string>("RolName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RolID");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RolID = 1,
                            RolName = "Admin"
                        },
                        new
                        {
                            RolID = 2,
                            RolName = "Estudiante"
                        },
                        new
                        {
                            RolID = 3,
                            RolName = "Docente"
                        });
                });

            modelBuilder.Entity("Staticaly.Server.Models.SubProyectos", b =>
                {
                    b.Property<int>("SubproyectoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubproyectoID"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool?>("Editando")
                        .HasColumnType("bit");

                    b.Property<int>("ProyectoID")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("UsuarioID")
                        .HasColumnType("int");

                    b.HasKey("SubproyectoID");

                    b.HasIndex("ProyectoID");

                    b.HasIndex("UsuarioID");

                    b.ToTable("SubProyectos");
                });

            modelBuilder.Entity("Staticaly.Server.Models.TiposEquipos", b =>
                {
                    b.Property<int>("TipoEquipoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TipoEquipoID"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("TipoEquipoID");

                    b.ToTable("TiposEquipos");

                    b.HasData(
                        new
                        {
                            TipoEquipoID = 1,
                            Nombre = "Publico"
                        },
                        new
                        {
                            TipoEquipoID = 2,
                            Nombre = "Estudiante"
                        },
                        new
                        {
                            TipoEquipoID = 3,
                            Nombre = "Docente"
                        });
                });

            modelBuilder.Entity("Staticaly.Server.Models.User", b =>
                {
                    b.Property<int>("UsuarioID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsuarioID"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("EmailVerified")
                        .HasColumnType("bit");

                    b.Property<byte[]>("Imagen")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Puntos")
                        .HasColumnType("int");

                    b.Property<int>("RangoID")
                        .HasColumnType("int");

                    b.Property<int>("RolID")
                        .HasColumnType("int");

                    b.Property<string>("VerificationToken")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("UsuarioID");

                    b.HasIndex("RangoID");

                    b.HasIndex("RolID");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            UsuarioID = 1,
                            Apellido = "Admin",
                            Email = "staticaly.services@gmail.com",
                            EmailVerified = true,
                            Nombre = "Admin",
                            Password = "$2a$12$wM8vSxJF5IO27LsmTeheheB.durdm4GUJp4RD9pLon4/fYTlR6mbS",
                            Puntos = 100000,
                            RangoID = 10,
                            RolID = 1
                        });
                });

            modelBuilder.Entity("Staticaly.Server.Models.UsuariosEquipos", b =>
                {
                    b.Property<int>("UsuarioEquipoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsuarioEquipoID"));

                    b.Property<int>("EquipoID")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaUnir")
                        .HasColumnType("datetime2");

                    b.Property<int>("PermisoID")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioID")
                        .HasColumnType("int");

                    b.HasKey("UsuarioEquipoID");

                    b.HasIndex("EquipoID");

                    b.HasIndex("PermisoID");

                    b.HasIndex("UsuarioID");

                    b.ToTable("UsuariosEquipos");
                });

            modelBuilder.Entity("Staticaly.Server.Models.Calificaciones", b =>
                {
                    b.HasOne("Staticaly.Server.Models.Comentarios", "Comentario")
                        .WithMany()
                        .HasForeignKey("ComentarioID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Staticaly.Server.Models.User", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Comentario");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Staticaly.Server.Models.Comentarios", b =>
                {
                    b.HasOne("Staticaly.Server.Models.Publicaciones", "Publicacion")
                        .WithMany()
                        .HasForeignKey("PublicacionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Staticaly.Server.Models.User", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Publicacion");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Staticaly.Server.Models.Cuestionarios", b =>
                {
                    b.HasOne("Staticaly.Server.Models.Equipos", "Equipo")
                        .WithMany()
                        .HasForeignKey("EquipoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Staticaly.Server.Models.User", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipo");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Staticaly.Server.Models.DatosSubProyecto", b =>
                {
                    b.HasOne("Staticaly.Server.Models.SubProyectos", "Subproyecto")
                        .WithMany()
                        .HasForeignKey("SubproyectoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subproyecto");
                });

            modelBuilder.Entity("Staticaly.Server.Models.Ejercicios", b =>
                {
                    b.HasOne("Staticaly.Server.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UsuarioID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Staticaly.Server.Models.EjerciciosPreguntas", b =>
                {
                    b.HasOne("Staticaly.Server.Models.Ejercicios", "Ejercicios")
                        .WithMany()
                        .HasForeignKey("EjercicioID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ejercicios");
                });

            modelBuilder.Entity("Staticaly.Server.Models.EjerciciosRespuestas", b =>
                {
                    b.HasOne("Staticaly.Server.Models.EjerciciosPreguntas", "EjerciciosPreguntas")
                        .WithMany()
                        .HasForeignKey("EjercicioPreguntaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Staticaly.Server.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UsuarioID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EjerciciosPreguntas");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Staticaly.Server.Models.Equipos", b =>
                {
                    b.HasOne("Staticaly.Server.Models.TiposEquipos", "TipoEquipo")
                        .WithMany()
                        .HasForeignKey("TipoEquipoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TipoEquipo");
                });

            modelBuilder.Entity("Staticaly.Server.Models.OpcionesCuestionario", b =>
                {
                    b.HasOne("Staticaly.Server.Models.Preguntas", "Pregunta")
                        .WithMany()
                        .HasForeignKey("PreguntaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pregunta");
                });

            modelBuilder.Entity("Staticaly.Server.Models.Preguntas", b =>
                {
                    b.HasOne("Staticaly.Server.Models.Cuestionarios", "Cuestionario")
                        .WithMany()
                        .HasForeignKey("CuestionarioID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cuestionario");
                });

            modelBuilder.Entity("Staticaly.Server.Models.Proyectos", b =>
                {
                    b.HasOne("Staticaly.Server.Models.Equipos", "Equipo")
                        .WithMany()
                        .HasForeignKey("EquipoID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Staticaly.Server.Models.User", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Equipo");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Staticaly.Server.Models.Publicaciones", b =>
                {
                    b.HasOne("Staticaly.Server.Models.User", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Staticaly.Server.Models.Reportes", b =>
                {
                    b.HasOne("Staticaly.Server.Models.Comentarios", "Comentarios")
                        .WithMany()
                        .HasForeignKey("ComentarioID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Staticaly.Server.Models.Publicaciones", "publicaciones")
                        .WithMany()
                        .HasForeignKey("PublicacionID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Staticaly.Server.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UsuarioID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Comentarios");

                    b.Navigation("User");

                    b.Navigation("publicaciones");
                });

            modelBuilder.Entity("Staticaly.Server.Models.RespuestasCuestionario", b =>
                {
                    b.HasOne("Staticaly.Server.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UsuarioID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Staticaly.Server.Models.SubProyectos", b =>
                {
                    b.HasOne("Staticaly.Server.Models.Proyectos", "Proyecto")
                        .WithMany()
                        .HasForeignKey("ProyectoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Staticaly.Server.Models.User", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Proyecto");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Staticaly.Server.Models.User", b =>
                {
                    b.HasOne("Staticaly.Server.Models.Rango", "Rango")
                        .WithMany()
                        .HasForeignKey("RangoID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Staticaly.Server.Models.Rol", "Rol")
                        .WithMany()
                        .HasForeignKey("RolID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rango");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("Staticaly.Server.Models.UsuariosEquipos", b =>
                {
                    b.HasOne("Staticaly.Server.Models.Equipos", "Equipo")
                        .WithMany()
                        .HasForeignKey("EquipoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Staticaly.Server.Models.Permisos", "Permiso")
                        .WithMany()
                        .HasForeignKey("PermisoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Staticaly.Server.Models.User", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipo");

                    b.Navigation("Permiso");

                    b.Navigation("Usuario");
                });
#pragma warning restore 612, 618
        }
    }
}
